#
# AMD SEV (Secure Encrypted Virtualization) detection module
#
# Copyright (c) 2026 Advanced Micro Devices, Inc.
# All rights reserved.
#

.PATH: ${.CURDIR}

KMOD=	amd_sev
SRCS=	amd_sev.c

.include <bsd.kmod.mk>
