#
# AMD SEV (Secure Encrypted Virtualization) tests
#
# Copyright (c) 2026 Advanced Micro Devices, Inc.
# All rights reserved.
#

TESTSDIR=	${TESTSBASE}/sys/amd/sev

ATF_TESTS_C+=	sev_test

.include <bsd.test.mk>
